name: Assignment Autotest

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Run assignment autotest
      run: |
        cd assignment-autotest
        ./run-autotest.sh
